### ISSUE TITLE
Eviternity death exit

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#147]
Hello there!

Death exits in Eviternity dont work. I did change some comp flags to see if thats the issue, but no, death exit doesnt advance player to next level, it just restarts map.

**Comment by rfomin** [comment]
This is due to the "Zombie players can leave levels" compatibility flag, which should be set to "Yes".
I guess we should fix that in the next release. Thanks for the report!

**Comment by Aaron03071991** [comment]
Even when flag is set to "yes", death exit still doesnt work and sends player back to start of the map.

**Comment by rfomin** [comment]
> flag is set to "yes"

Are you sure? I test death exit on map05->map06 it seems to work.

**Comment by Aaron03071991** [comment]
Ok it works, turns out that:
1. I did change flag to "yes"
2. I was loading a save game that I did right before exit
3. Death exit did work only after I restarted map

In short, flags dont change for already saved games.
Sorry for the fuss.

**Comment by fabiangreffrath** [comment]
This is now enabled by default:
https://github.com/fabiangreffrath/woof/commit/dd4a0da1d871bff8065b6616b00b4af77bfe6b3e
