### ISSUE TITLE
Odd padding on messages again

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#2054]
I noticed with 15.0.0, hud messages have awkward padding again, pushing them a few pixels to the right when they're not supposed to.

**Comment by fabiangreffrath** [comment]
Probably the wrong string width function is in use again.

**Comment by rfomin** [comment]
I added 2px offset: https://github.com/fabiangreffrath/woof/blob/71bb824efa47deb053d6a424a3e42afa7b724c16/base/all-all/sbardef.lmp#L1051
Is it supposed to be 0?

**Comment by Terraformer9x** [comment]
> I added 2px offset:
> 
> https://github.com/fabiangreffrath/woof/blob/71bb824efa47deb053d6a424a3e42afa7b724c16/base/all-all/sbardef.lmp#L1051
> 
> Is it supposed to be 0?

Yes, Vanilla Doom displays messages at 0,0.

**Comment by rfomin** [comment]
Fixed in 6abbfdf

**Comment by fabiangreffrath** [comment]
> Boom widgets have a 2px left margin, Doom widgets don't.

Right-aligned Boom widgets are still missing their 2px gap to the right side.

Maybe this?

```patch
--- a/src/st_stuff.c
+++ b/src/st_stuff.c
@@ -846,7 +846,7 @@ static void UpdateLines(sbarelem_t *elem)
         }
         else if (elem->alignment & sbe_h_right)
         {
-            line->xoffset -= totalwidth;
+            line->xoffset -= totalwidth + 2;
         }
         line->totalwidth = totalwidth;
     }
```

**Comment by rfomin** [comment]
> Right-aligned Boom widgets are still missing their 2px gap to the right side.

> Maybe this?

No, we can add the same 2px offset in the SBARDEF lump, just for widgets that align to the right (`sbe_h_right` flag).

**Comment by rfomin** [comment]
> Right-aligned Boom widgets are still missing their 2px gap to the right side.

Fixed in f16bbb7
